# Data
DATASET_RAW = '../data/dataset_raw.csv'
DATASET_PROCESSED = '../data/dataset_processed.csv'
DATASET_LEAN = '../data/dataset_lean.csv'
DATASET_DUMMIES = '../data/dataset_dummies.csv'
DATASET_TRANSFORMED = '../data/dataset_transformed.csv'
DATASET_CLUSTERED = '../data/dataset_clustered.csv'
DATASET_DEPLOY = '../data/dataset_deploy.csv'
DATASET_DEPLOYED = '../data/dataset_deployed.csv'

# Images Illustrations
WALLPAPER = '../images/illustrations/wallpaper.png'
BOXPLOT = '../images/illustrations/boxplot.png'
SCATTERPLOT = '../images/illustrations/scatterplot.png'
HISTPLOT = '../images/illustrations/histplot.png'
KDEPLOT = '../images/illustrations/kdeplot.png'
HEATMAP = '../images/illustrations/heatmap.png'
PAIRPLOTS = '../images/illustrations/pairplots.png'
ACCURACY = '../images/illustrations/accuracy.png'
PRECISION = '../images/illustrations/precision.png'
RECALL = '../images/illustrations/recall.png'
F1_SCORE = '../images/illustrations/f1_score.png'
ROC_AUC = '../images/illustrations/roc_auc.png'
AUPRC = '../images/illustrations/auprc.png'
AP = '../images/illustrations/ap.png'
CONFUSION_MATRIX = '../images/illustrations/confusion_matrix.png'
TIME = '../images/illustrations/time.png'
MAE = '../images/illustrations/mae.png'
MSE = '../images/illustrations/mse.png'
RMSE = '../images/illustrations/rmse.png'
R2 = '../images/illustrations/r2.png'
ELBOW_METHOD = '../images/illustrations/elbow_method.png'
SILHOUETTE_METHOD = '../images/illustrations/silhouette_method.png'
DUMMY = '../images/illustrations/dummy.png'
CLASSIFICATION_TREE = '../images/illustrations/classification_tree.png'
LOGISTIC_REGRESSION = '../images/illustrations/logistic_regression.png'
NAIVE_BAYES = '../images/illustrations/naive_bayes.png'
KNN = '../images/illustrations/knn.png'
SVM = '../images/illustrations/svm.png'
LINEAR_REGRESSION = '../images/illustrations/linear_regression.png'
POLYNOMIAL_REGRESSION = '../images/illustrations/polynomial_regression.png'
REGRESSION_TREE = '../images/illustrations/regression_tree.png'
KNR = '../images/illustrations/knr.png'
RANDOM_FOREST_REGRESSOR = '../images/illustrations/random_forest_regressor.png'
XGBOOST_REGRESSOR = '../images/illustrations/xgboost_regressor.png'
K_MEANS = '../images/illustrations/k_means.png'
MEAN_SHIFT = '../images/illustrations/mean_shift.png'
DBSCAN = '../images/illustrations/dbscan.png'
ONE_HOT_ENCODER = '../images/illustrations/one_hot_encoder.png'
STANDARD_SCALER = '../images/illustrations/standard_scaler.png'
POWER_TRANSFORMATION = '../images/illustrations/power_transformation.png'
MIN_MAX_SCALER = '../images/illustrations/min_max_scaler.png'
ROBUST_SCALER = '../images/illustrations/robust_scaler.png'
PCA = '../images/illustrations/pca.png'
ROS = '../images/illustrations/ros.png'
RUS = '../images/illustrations/rus.png'
PIPELINE = '../images/illustrations/pipeline.png'
K_FOLD = '../images/illustrations/k_fold.png'
STRATIFIED_K_FOLD = '../images/illustrations/stratified_k_fold.png'
GRID_SEARCH = '../images/illustrations/grid_search.png'

# Images Outputs
SCHEDULE = '../images/outputs/schedule.png'

# Reports
EDA_0 = '../reports/eda_0.html'
EDA_1 = '../reports/eda_1.html'

# Models
MODEL_CLASSIFICATION_JOBLIB = '../models/model_classification.joblib'
MODEL_CLASSIFICATION_PKL = '../models/model_classification.pkl'

# Values
RANDOM_STATE = 42